export const iettsTexts = {
  pageTitle: "IETTS Kayıtları",
  searchButton: "Filtrele",
  clearButton: "Temizle",
  loadFailed: "IETTS kayıtları getirilemedi.",
  noPermission: "Bu sayfayı görüntüleme yetkiniz bulunmuyor.",
  noRecords: "Kayıt bulunamadı.",
  loading: "IETTS kayıtları yükleniyor.",
  exportCsv: "CSV indir",
  exportJson: "JSON indir",
  exportCurrentPageHint: "Dışa aktarma yalnızca görünen sayfadaki kayıtları içerir.",
  dateFilterPlaceholder: "YYYY-MM-DD",
  convertToCustomer: "Müşteriye Dönüştür",
  viewCustomerRecord: "Müşteri tam kayıt formuna git",
  convertConfirmTitle: "Müşteriye Dönüştür",
  convertConfirmMessage:
    "Bu IETTS kaydı müşteriye çevrildikten sonra sayfa Müşteri Tam Kayıt formuna yönlendirilecektir.",
  cancel: "İptal",
  continue: "Devam Et",
  convertFailed: "IETTS kaydı müşteriye dönüştürülemedi.",
  converting: "Dönüştürülüyor...",
  columns: {
    actions: "İşlemler",
    documentNumber: "Belge No",
    companyName: "İşletme Ünvanı",
    businessName: "İşletme Adı",
    businessAddress: "İşletme Adresi",
    documentIssueDate: "Belge Veriliş Tarihi",
    documentStatus: "Belge Durumu",
    city: "İl",
    district: "İlçe",
    createdAt: "Oluşturma",
  },
} as const;
