export const authTexts = {
  loginTitle: 'Giriş yapın',
  phonePlaceholder: '05XXXXXXXXX',
  phoneSubmitLabel: 'OTP Kodu Gönder',
  phoneSubmittingLabel: 'Gönderiliyor...',
  forgotPasswordLabel: 'Şifremi Unuttum',
  phoneInvalidMessage: 'Telefon numarası 05XXXXXXXXX formatında olmalıdır.',
  otpRequestFailedMessage: 'OTP kodu gönderilemedi. Lütfen tekrar deneyin.',
  otpInstruction: 'Telefon numaranıza gönderilen 6 haneli kodu girin:',
  otpPlaceholder: '000000',
  remainingTimeLabel: 'Kalan süre',
  backLabel: 'Geri',
  verifyLabel: 'Doğrula',
  otpInvalidMessage: 'OTP kodu 6 haneli olmalıdır.',
  logoAlt: 'CRM',
} as const;
