export const authTexts = {
  loginTitle: "Giriş yapın",
  phonePlaceholder: "05XXXXXXXXX",
  phoneSubmitLabel: "OTP Kodu Gönder",
  phoneSubmittingLabel: "Gönderiliyor...",
  forgotPasswordLabel: "Şifremi Unuttum",
  phoneInvalidMessage: "Telefon numarası 05XXXXXXXXX formatında olmalıdır.",
  otpRequestFailedMessage: "OTP kodu gönderilemedi. Lütfen tekrar deneyin.",
  otpInstruction: "Telefon numaranıza gönderilen 6 haneli kodu girin:",
  otpPlaceholder: "000000",
  remainingTimeLabel: "Kalan süre",
  backLabel: "Geri",
  verifyLabel: "Doğrula",
  otpVerifyingLabel: "Doğrulanıyor...",
  otpInvalidMessage: "OTP kodu 6 haneli olmalıdır.",
  otpVerifyFailedMessage: "Güvenlik kodu hatalı.",
  passwordPlaceholder: "Şifre",
  rememberMeLabel: "Beni Hatırla",
  passwordSubmitLabel: "Giriş Yap",
  passwordSubmittingLabel: "Giriş yapılıyor...",
  passwordInvalidMessage: "Şifre zorunludur.",
  passwordLoginFailedMessage: "Kimlik bilgileri hatalı.",
  logoAlt: "CRM",
} as const;
